# Botón "Sponsor" en GitHub
# Descomentar y ajustar si se habilita financiamiento del proyecto

# github: olimpus-soft
# patreon: olimpussoft
# open_collective: olimpussoft
# custom: https://olimpussoft.com/sponsor
