name: Pull Request Labeler

on:
  pull_request_target:
    paths:
      - '**/*'

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: [self-hosted, linux, x64, vps-ephemeral]
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labels.yml"
